-- 코드를 입력하세요
-- ONLINE_SALE(상품판매ID, 회원ID, 상품ID, 판매량, 판매일)
-- OFFLINE_SALE(상품판매ID, 상품ID, 판매량, 판매일)
-- 동일한 날짜, 상품 ID 조합에 대해서는 하나의 판매 데이터만 존재.
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, 
       PRODUCT_ID, 
       USER_ID, 
       SALES_AMOUNT
FROM (
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
UNION ALL
SELECT SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
) AS SALES
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;