-- 코드를 작성해주세요
# SELECT ID, 
# CASE WHEN ROUND(CONVERT(float, SIZE_OF_COLONY) / SUM(SIZE_OF_COLONY) OVER(), 2) * 100 >= 25 THEN 'CRITICAL' 
# WHEN 26 <= ROUND(CONVERT(float, SIZE_OF_COLONY) / SUM(SIZE_OF_COLONY) OVER(), 2) * 100 >= 50 THEN 'HIGH' 
# WHEN 51 <= ROUND(CONVERT(float, SIZE_OF_COLONY) / SUM(SIZE_OF_COLONY) OVER(), 2) * 100 >= 75 THEN 'MEDIUM'
# WHEN 76 <= ROUND(CONVERT(float, SIZE_OF_COLONY) / SUM(SIZE_OF_COLONY) OVER(), 2) * 100 >= 100 THEN 'LOW' as COLONY_NAME
# FROM ECOLI_DATA
# ORDER BY ID ASC;
# ROUND((SUM(tot_amt) / (SELECT SUM(tot_amt) FROM [RFM_BASE_SEG2]))*100, 2)

SELECT ID, 
CASE WHEN size = 1 THEN 'CRITICAL'
WHEN size = 2 THEN 'HIGH'
WHEN size = 3 THEN 'MEDIUM'
WHEN size = 4 THEN 'LOW'
END AS COLONY_NAME
FROM (
    SELECT ID, SIZE_OF_COLONY, NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS size FROM ECOLI_DATA) as RankedColony
ORDER BY ID ASC;