-- 코드를 작성해주세요
-- 세대별 PARENT_ID가 NULL일 애들 COUNT하면 될 거 같기도..
WITH recursive CTE as(
    SELECT ID, 1 as GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 부모 개체의 ID를 참조하여 세대 증가
    SELECT B.ID, A.GENERATION+1
    FROM CTE AS A
    INNER JOIN ECOLI_DATA AS B ON B.PARENT_ID = A.ID
    
)

-- 각 세대별로 자식이 없는 (LEAF NODE) 개체 수 계산
SELECT count(*) as COUNT, GENERATION
FROM CTE
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY CTE.GENERATION ASC;