-- 코드를 입력하세요
# SELECT HOUR(DATETIME), MINUTE(DATETIME)
# FROM ANIMAL_OUTS

SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE (HOUR(DATETIME) BETWEEN 9 AND 19)
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME);