-- 코드를 작성해주세요
-- ITEM_INFO 아이템ID, 아이템 명, 아이템 희귀도, 아이템 가격
-- ITEM_TREE 아이템ID, PARENT 아이템ID
SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i
JOIN ITEM_TREE t ON i.ITEM_ID = t.ITEM_ID
WHERE t.PARENT_ITEM_ID in (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY i.ITEM_ID DESC;