-- 코드를 작성해주세요
# SELECT COUNT(*) as FISH_COUNT
# FROM FISH_INFO i
# JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE
# WHERE i.FISH_TYPE in (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME in ('BASS', 'SNAPPER'))

SELECT COUNT(*) as FISH_COUNT
FROM FISH_INFO
WHERE FISH_TYPE in (SELECT FISH_TYPE FROM FISH_NAME_INFO WHERE FISH_NAME in ('BASS', 'SNAPPER'))